name: CI

on:
    push:
        branches: [ 6.0 ]
    pull_request:
        branches: [ 6.0 ]

permissions:
    contents: read

env:
    XDEBUG_MODE: coverage

jobs:
    build:
        runs-on: ubuntu-latest
        #        permissions:
        #            contents: write
        strategy:
            matrix:
                php-versions: [ '8.4' ]
                composer-prefer: [ '', '--prefer-lowest' ]

        steps:
            -   uses: actions/checkout@v6
